<?php

declare(strict_types=1);

namespace MyApp\Resource\Page;

use BEAR\Resource\ResourceObject;
use BEAR\Sunday\Inject\ResourceInject;
use Polidog\UsephpBearRenderer\UsePhpActionResponder;

/**
 * GET  /counter?count=42  — initial render with snapshot-backed useState.
 * POST /counter            — usephp.js partial action POST. The form is
 *                            generated by the PSX template's onClick handlers
 *                            and carries `_usephp_action` + `_usephp_snapshot`.
 *
 * The transition rules (inc/dec/reset) are owned by the App resource at
 * `app://self/counter`. This Page only:
 *   - asks the App resource to compute next/prev/reset for the current count
 *     and exposes them as template props (so the template's onClick payloads
 *     are precomputed values),
 *   - delegates the action POST to the {@see UsePhpActionResponder} which
 *     restores the snapshot, applies the setState, and renders the partial
 *     HTML that usephp.js swaps into `[data-usephp]`.
 */
final class Counter extends ResourceObject
{
    use ResourceInject;

    public function __construct(
        private readonly UsePhpActionResponder $responder,
    ) {}

    public function onGet(int $count = 0): static
    {
        $this->body = $this->buildProps($count);

        return $this;
    }

    public function onPost(): static
    {
        $post = $_POST;
        $server = $_SERVER;

        // Recover the count this action will produce so we can precompute
        // next/prev/reset for the *post-action* render. The responder will
        // also apply the setState — we only peek at the value.
        $newCount = $this->extractActionValue($post);

        $props = $this->buildProps($newCount);
        $this->body = $props;

        $partial = $this->responder->handle($this, $post, $server, $props);
        if ($partial !== null) {
            $this->view = $partial;
        }

        return $this;
    }

    /**
     * Build the prop bag the PSX template consumes. `next`/`prev`/`reset`
     * come from the App\Counter resource so the template doesn't bake the
     * transition rules into the view layer.
     *
     * @return array{count:int, next:int, prev:int, reset:int}
     */
    private function buildProps(int $count): array
    {
        $next = (int) $this->resource->post('app://self/counter', ['count' => $count, 'action' => 'inc'])->body['count'];
        $prev = (int) $this->resource->post('app://self/counter', ['count' => $count, 'action' => 'dec'])->body['count'];
        $reset = (int) $this->resource->post('app://self/counter', ['count' => $count, 'action' => 'reset'])->body['count'];

        return [
            'count' => $count,
            'next' => $next,
            'prev' => $prev,
            'reset' => $reset,
        ];
    }

    /**
     * Pull the setState payload value out of `_usephp_action` without
     * applying it (the responder applies it for real). Falls back to 0 for
     * non-action POSTs so the page still renders sensibly.
     *
     * @param array<string, mixed> $post
     */
    private function extractActionValue(array $post): int
    {
        $actionJson = $post['_usephp_action'] ?? null;
        if (!\is_string($actionJson)) {
            return 0;
        }
        try {
            /** @var array{type?:string, payload?:array{value?:mixed}} $action */
            $action = \json_decode($actionJson, true, 512, \JSON_THROW_ON_ERROR);
        } catch (\JsonException) {
            return 0;
        }
        if (($action['type'] ?? null) !== 'setState') {
            return 0;
        }
        return (int) ($action['payload']['value'] ?? 0);
    }
}
